configoptions="
--enable-cli \
--enable-bcmath \
--enable-calendar \
--enable-exif \
--enable-ftp \
--enable-mbstring \
--enable-pcntl \
--enable-soap \
--enable-sockets \
--enable-wddx \
--enable-zip \
--enable-fpm \
--enable-intl \
--with-openssl \
--with-zlib \
--with-readline \
--with-openssl \
--with-gettext \
--with-pear \
--with-curl \
--with-gd \
--with-mcrypt \
--with-mysql \
--with-mysqli \
--with-pdo-mysql \
--with-jpeg-dir \
--with-png-dir \
--with-xsl
"